### ISSUE TITLE
Make k8s dashboard work

### ISSUE THREAD

**Issue by smanpathak** [platform9/prometheus-plus#10]
The new dashboard being added as part of https://github.com/platform9/prometheus-plus/pull/9 does not work. We need to fix the queries/data sources.

**Comment by mugdha-adhav** [comment]
Resolved in #9 

Added following fixes for k8s dashboard

- Fixed node and namespace queries to return node name and actual namespace in templating.
- Namespace needs to be replaced to exported_namespace as namespace is always pf9-monitoring and exported_namespace returns actual list of namespaces.
