### ISSUE TITLE
Make dashboard "X" default

### ISSUE THREAD

**Issue by smanpathak** [platform9/prometheus-plus#11]
Grafana dashboards are not default presently. As a result accessing grafana UI from the DU loads the general page and requires user to choose a dashboard. We need to designate k8s dashboard as default. I believe it's possible by API calls to grafana. Perhaps we can spin up a background job when grafana pod comes up and does a PUT request to set the default dashboard.

**Comment by mugdha-adhav** [comment]
Found an alternative solution to this problem. We can replace the home dashboard with k8s dashboard. Anyways we don't need the home dashboard as most of the configs are already set and loaded.

For the above mentioned approach, we will need to mount the grafana-dashboard-k8s-cluster.json file at /usr/share/grafana/public/dashboards/home.json

@smanpathak
